name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # UI & Design
  google_fonts: ^5.1.0
  flutter_iconly: ^1.0.2
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  http: ^1.3.0         # Mis à jour pour compatibilité avec google_fonts 5.1.0
  shared_preferences: ^2.0.18  # Pour sauvegarder l'historique des messages
  intl: ^0.18.0
  image_picker: ^0.8.7+5

  # Utilitaires
  provider: ^6.0.0
  url_launcher: ^6.1.10
  typed_data: ^1.3.2
  archive: ^3.4.0

  # Base de données locale
  sqflite: ^2.3.2
  path_provider: ^2.1.1
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.0+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/profile7.jpg
    - assets/images/blog1.jpg
    - assets/images/blog2.jpg
    - assets/images/guerre-des-semences.jpg
    - assets/profile/
    - assets/profile/profile14.jpeg
    - assets/profile/profile3.jpg
    - assets/profile/profile1.jpeg
    - assets/profile/profile2.jpg
    - assets/profile/profile4.jpeg
    - assets/profile/profile5.jpeg
    - assets/profile/profile6.jpeg
    - assets/images/corn_seeds.jpg
    - assets/images/pesticide.jpg
    - assets/images/blog1.jpg
    - assets/images/blog2.jpg
    - assets/profile.jpg
    - assets/services/
    - assets/images/fertilizer.png
