// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnmrLsnxpWcl0KbefoMO6VJ6f8Dm5BRkQ',
    appId: '1:677802576918:web:your_web_app_id',
    messagingSenderId: '677802576918',
    projectId: 'felahtk',
    authDomain: 'felahtk.firebaseapp.com',
    storageBucket: 'felahtk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnmrLsnxpWcl0KbefoMO6VJ6f8Dm5BRkQ',
    appId: '1:677802576918:android:e7bd0d04efe3c572d67937',
    messagingSenderId: '677802576918',
    projectId: 'felahtk',
    storageBucket: 'felahtk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmrLsnxpWcl0KbefoMO6VJ6f8Dm5BRkQ',
    appId: '1:677802576918:ios:your_ios_app_id',
    messagingSenderId: '677802576918',
    projectId: 'felahtk',
    storageBucket: 'felahtk.firebasestorage.app',
    iosBundleId: 'com.example.agricplant.agriplant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnmrLsnxpWcl0KbefoMO6VJ6f8Dm5BRkQ',
    appId: '1:677802576918:ios:your_ios_app_id',
    messagingSenderId: '677802576918',
    projectId: 'felahtk',
    storageBucket: 'felahtk.firebasestorage.app',
    iosBundleId: 'com.example.agricplant.agriplant',
  );
}
